site_name: Liderahenk Dokümanlar
repo_name: Liderahenk
repo_url: https://github.com/Pardus-LiderAhenk

# docs_dir: lider/docs_suffix_structure
docs_dir: docs
nav:
  - Ana Sayfa: index.md
  - Kurulum:
        - Sistem Gereksinimleri: installation/lider/systemRequirements.md
        - Sunucu Kurulumu(Lider): installation/lider/lider.md
        - İstemci Kurulumu(Ahenk): installation/ahenk/ahenk.md
        - Lider 3.0 Sürümüne Yükseltme: installation/lider/liderUpgrade.md
  - Liderahenk 2.0:
        - Oturum Açma: lider2.0/giris.md
        - Kullanım:
            - Anlık Mesaj: lider2.0/computer_management/sistem/anlik_mesaj.md
            - Dosya Paylaşımı: lider2.0/computer_management/sistem/dosya_paylasimi.md
            - Dosya Yönetimi: lider2.0/computer_management/sistem/dosya_yonetimi.md
            - İstemci Bilgileri: lider2.0/computer_management/sistem/istemci_bilgileri.md
            - İstemci Oturum Açma Ayarları: lider2.0/computer_management/sistem/istemci_oturum_acma_ayarlari.md
            - Kaynak Kullanımı: lider2.0/computer_management/sistem/kaynak_kullanimi.md
            - Oturum Yönetimi: lider2.0/computer_management/sistem/oturum_yonetimi.md
            - Root Parola Yönetimi: lider2.0/computer_management/sistem/root_parola_yonetimi.md
            - Sistem Gözlemcisi: lider2.0/computer_management/sistem/sistem_gozlemcisi.md
            - Uzak Masaüstü: lider2.0/computer_management/sistem/uzak_masaustu.md
            - Yerel Kullanıcı Yönetimi: lider2.0/computer_management/sistem/yerel_kullanici_yonetimi.md
            - İstemci Paket Depoları: lider2.0/computer_management/paket/istemci_paket_depolari.md
            - İstemci Paketlerini Listele ve Kaldır: lider2.0/computer_management/paket/istemci_paketlerini_listele_ve_kaldir.md
            - Paket Kur ve Kaldır: lider2.0/computer_management/paket/paket_kur_veya_kaldir.md
            - Servis Yönetimi: lider2.0/computer_management/servis/servis_yonetimi.md
            - Betik Listesi: lider2.0/computer_management/betik/betik_listesi.md
            - Betik Tanımı: lider2.0/computer_management/betik/betik_tanimi.md
            - SSH: lider2.0/computer_management/SSH/SSH.md
            - Ağ Yönetimi: lider2.0/computer_management/guvenlik/ag_yonetimi.md
            - USB Yönetimi: lider2.0/computer_management/guvenlik/usb_yonetimi.md
            - Geçmiş: lider2.0/computer_management/gecmis/gecmis.md
            - Ahenk Kur: lider2.0/computer_management/ahenkkur/ahenk_kur.md
        - Kullanıcı Yönetimi:
            - Kullanıcı İşlemleri: lider2.0/user_management/kullaniciislemleri/kullaniciislemleri.md
            - AD Senkronizasyon: lider2.0/user_management/ADsenkronizasyon/ADsenkronizasyon.md
        - Grup Yönetimi:
            - Kullanıcı Grup Yönetimi: lider2.0/group_management/kullanicigrupyönetimi/kullanicigrupyonetimi.md
            - Genel Ekran: lider2.0/group_management/istemcigrupyonetimi/genelekran.md
            - Sistem: lider2.0/group_management/istemcigrupyonetimi/sistem.md
            - Betik: lider2.0/group_management/istemcigrupyonetimi/betik.md
            - Paket: lider2.0/group_management/istemcigrupyonetimi/paket.md
            - Kullanıcı Yetkilendirme (Sudo): lider2.0/group_management/kullaniciyetkilendirme/kullaniciyetkilendirme.md
            - Politika Yönetimi: lider2.0/group_management/politikayonetimi/politika_yonetimi.md
        - Raporlar:
            - Detaylı İştemci Raporu: lider2.0/reports/detayli_istemci_raporu.md
            - Çalıştırılan Görevler Raporu: lider2.0/reports/calistirilan_görev_raporu.md
            - Sistem Güncesi Raporu: lider2.0/reports/sistem_güncesi_raporu.md
        - Ayarlar:
            - Konsol Kullanıcısı Ayarları: lider2.0/settings/sunucuayarlari/konsolkullanicisiayarlari.md
            - LDAP Erişim Ayarları: lider2.0/settings/sunucuayarlari/ldaperisimayarlari.md
            - LDAP Ayarları: lider2.0/settings/sunucuayarlari/ldapayrlari.md
            - XMPP Ayarları: lider2.0/settings/sunucuayarlari/xmppayarlari.md
            - Dosya Sunucu Ayarları: lider2.0/settings/sunucuayarlari/dosyasunucuayarlari.md
            - Diğer Ayarları: lider2.0/settings/sunucuayarlari/digerayarlar.md
            - Sistem Gözlemcisi Tanımlama: lider2.0/settings/sistemgozlemcitanımlari/sistemgozlemcisi.md
            - Betik Tanımları: lider2.0/settings/betiktanimlari/betik.md
            - Kayıt Şablonları: lider2.0/settings/kayitsablonlari/kayitsablonlari.md
  - Liderahenk 3.0:
        - Kontrol Paneli: lider3.0/index.md
        - Oturum Açma: lider3.0/login.md
        - İstemci Yönetimi:
            - İstemci Yönetimi:
                - Genel Bilgi: lider3.0/computerManagement/computerManagement.md
                - Anlık Mesaj: lider3.0/computerManagement/computerManagement/instantMessage.md
                - Dosya Paylaşımı: lider3.0/computerManagement/computerManagement/fileShare.md
                - Dosya Yönetimi: lider3.0/computerManagement/computerManagement/fileManagement.md
                - İstemci Bilgileri: lider3.0/computerManagement/computerManagement/computerInformation.md
                - İstemci Oturum Açma Ayarları: lider3.0/computerManagement/computerManagement/computerLoginSettings.md
                - Kaynak Kullanımı: lider3.0/computerManagement/computerManagement/resourcesUsage.md
                - Oturum Yönetimi: lider3.0/computerManagement/computerManagement/sessionPowerManagement.md
                - Root Parola Yönetimi: lider3.0/computerManagement/computerManagement/rootPasswordManagement.md
                - Sistem Gözlemcisi: lider3.0/computerManagement/computerManagement/systemMonitoring.md
                - Yerel Kullanıcı Yönetimi: lider3.0/computerManagement/computerManagement/localUserManagement.md
                - Depo Yönetimi: lider3.0/computerManagement/computerManagement/repositoryManagement.md
                - Kurulu Paket Yönetimi: lider3.0/computerManagement/computerManagement/installedPackageManagement.md
                - Paket Kur veya Kaldır: lider3.0/computerManagement/computerManagement/packageInstallUninstall.md
                - Paket Kontrolü: lider3.0/computerManagement/computerManagement/packageControl.md
                - Servis Yönetimi: lider3.0/computerManagement/computerManagement/serviceManagement.md                
                - Betik : lider3.0/computerManagement/computerManagement/script.md
                - Ağ Yönetimi: lider3.0/computerManagement/computerManagement/networkManagement.md
                - USB Yönetimi: lider3.0/computerManagement/computerManagement/usbManagement.md
                - Geçmiş: lider3.0/computerManagement/computerManagement/taskHistory.md
            - İstemci Grup Yönetimi:
                - Genel Bilgi: lider3.0/computerManagement/computerGroupManagement.md
                - USB Yönetimi: lider3.0/computerManagement/computerGroupManagement/usbManagement.md
                - Sistem Gözlemcisi: lider3.0/computerManagement/computerGroupManagement/systemMonitoring.md
                - Oturum Yönetimi: lider3.0/computerManagement/computerGroupManagement/sessionPowerManagement.md
                - Betik : lider3.0/computerManagement/computerGroupManagement/script.md
                - Root Parola Yönetimi: lider3.0/computerManagement/computerGroupManagement/rootPasswordManagement.md
                - Kayıt Bilgileri: lider3.0/computerManagement/computerGroupManagement/registirationInformation.md
                - Paket Kur veya Kaldır: lider3.0/computerManagement/computerGroupManagement/packageInstallUninstall.md
                - Paket Kontrolü: lider3.0/computerManagement/computerGroupManagement/packageControl.md
                - Anlık Mesaj: lider3.0/computerManagement/computerGroupManagement/instantMessage.md
                - Dosya Paylaşımı: lider3.0/computerManagement/computerGroupManagement/fileShare.md
                - İstemci Oturum Açma Ayarları: lider3.0/computerManagement/computerGroupManagement/computerLoginSettings.md
            - Zamanlanmış Görev: lider3.0/computerManagement/crontabManagement.md              
        - Kullanıcı Yönetimi:
            - Kullanıcı Yönetimi: lider3.0/userManagement/userManagement/userManagement.md
            - Kullanıcı Grup Yönetimi: lider3.0/userManagement/userGroupManagement/userGroupManagement.md
            - Kullanıcı Yetkilendirme(Sudo): lider3.0/userManagement/userAuthorizationSudo/userAuthorizationSudo.md
            - AD Yönetimi: lider3.0/userManagement/adManagement/adManagement.md
        - Politika Yönetimi:
            - Politikalar: lider3.0/policyManagement/policies/policies.md
            - Profiller: 
                - Genel Bilgi: lider3.0/policyManagement/profiles/profiles.md
                - İnternet Tarayıcı Ayarları: lider3.0/policyManagement/profiles/browserProfile.md
                - Rsyslog Ayarları: lider3.0/policyManagement/profiles/rsyslogProfile.md
                - Betik Ayarları: lider3.0/policyManagement/profiles/scriptProfile.md
                - Oturum Yönetim Ayarları: lider3.0/policyManagement/profiles/sessionManagementProfile.md
                - Sistem Gözlemcisi Ayarları: lider3.0/policyManagement/profiles/systemMonitoringProfile.md
                - USB Erişim Ayarları: lider3.0/policyManagement/profiles/usbProfile.md
        - Raporlar:
            - Detaylı İstemci Raporu: lider3.0/reports/detailedAgentReport/detailedAgentReport.md
            - Çalıştırılan Görev Raporu: lider3.0/reports/executedTaskReport/executedTaskReport.md
            - Sistem Güncesi Raporu: lider3.0/reports/systemLogReport/systemLogReport.md
            - Zamanlanmış Görev Raporu: lider3.0/reports/scheduledTaskReport/scheduledTaskReport.md
        - Ayarlar:
            - Arayüz Kullanıcı Ayarları: lider3.0/settings/consoleUserSettings/consoleUserSettings.md
            - Sunucu Ayarları:
                - Dizin Sunucu Ayarları: lider3.0/settings/serverSettings/ldapSettings.md
                - XMPP Sunucusu Ayarları: lider3.0/settings/serverSettings/xmppSettings.md
                - Dosya Sunucusu Ayarları: lider3.0/settings/serverSettings/fileServerSettings.md
                - Email Sunucusu Ayarları: lider3.0/settings/serverSettings/mailSettings.md
                - Diğer Ayarlar: lider3.0/settings/serverSettings/otherSettings.md
            - Sistem Gözlemcisi Ayarları: lider3.0/settings/systemMonitoringDefinitons/systemMonitoringDefinition.md
            - Betik Tanımları: lider3.0/settings/scriptDefinition/script.md
            - Kayıt Şablonları: lider3.0/settings/registirationTemplate/registirationTemplate.md      
        - Profil:
            - Kullanıcı Bilgileri: lider3.0/profile/userInformation/userInformation.md
            - Hesap Güvenliği: lider3.0/profile/accountSecurity/accountSecurity.md
            - Kullanım Geçmişi: lider3.0/profile/loginLogoutHistory/loginLogoutHistory.md
            - Grup Bilgileri: lider3.0/profile/groupInformation/groupInformation.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  # language: tr
  name: material
  logo: liderahenk-logo.png
  favicon: favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  direction: ltr
  
markdown_extensions:
  - admonition

plugins:
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "tr"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      languages:
        tr:
          name: Türkçe
          build: true
          site_name: "Liderahenk Dokümanlar"
        en:
          name: English
          build: true
          site_name: "Liderahenk Documents"
      nav_translations:
        en:
          Kontrol Paneli: Dashboard
          Oturum Açma: Login
          İstemci Yönetimi: Computer Management
          Genel Bilgi: General Information
          Anlık Mesaj: Instant Message
          Dosya Paylaşımı: File Share
          Dosya Yönetimi: File Management
          İstemci Bilgileri: Computer Information
          İstemci Oturum Açma Ayarları: Computer Login Settings
          Kaynak Kullanımı: Resources Usage
          Oturum Yönetimi: Session Power Management
          Root Parola Yönetimi: Root Password Management
          Sistem Gözlemcisi: System Monitoring
          Yerel Kullanıcı Yönetimi: Local User Management
          Depo Yönetimi: Repository Management
          Kurulu Paket Yönetimi: Installed Package Management
          Paket Kur veya Kaldır: Package Install Uninstall
          Paket Kontrolü: Package Control
          Servis Yönetimi: Service Management
          Betik: Script
          Ağ Yönetimi: Network Management
          USB Yönetimi: Usb Management
          Geçmiş: Task History
          İstemci Grup Yönetimi: Computer Group Management
          Kayıt Bilgileri: Registiration Information
          Zamanlanmış Görev: Crontab Management
          Kullanıcı Yönetimi: User Management
          Kullanıcı Grup Yönetimi: User Group Management
          Kullanıcı Yetkilendirme(Sudo): User Authorization (Sudo)
          AD Yönetimi: AD Management
          Politika Yönetimi: Policies Management
          Politikalar: Policies
          Profiller: Profiles
          İnternet Tarayıcı Ayarları: Browser Profile
          Rsyslog Ayarları: Rsyslog Profile
          Betik Ayarları: Script Profile
          Oturum Yönetim Ayarları: Session Management Profile
          Sistem Gözlemcisi Ayarları: System Monitoring Profile
          USB Erişim Ayarları: Usb Profile
          Raporlar: Reports
          Detaylı İstemci Raporu: Detailed Agent Report
          Çalıştırılan Görev Raporu: Executed Task Report
          Sistem Güncesi Raporu: System Log Report
          Zamanlanmış Görev Raporu: Scheduled Task Report
          Ayarlar: Settings
          Arayüz Kullanıcı Ayarları: Console User Settings
          Sunucu Ayarları: Server Settings
          Dizin Sunucu Ayarları: LDAP Settings
          XMPP Sunucusu Ayarları: XMPP Settings
          Dosya Sunucusu Ayarları: File Server Settings
          Email Sunucusu Ayarları: Mail Server Settings
          Diğer Ayarlar: Other Settings
          Betik Tanımları: Script Definition
          Kayıt Şablonları: Registiration Template
          Profil: Profile
          Kullanıcı Bilgileri: User Information
          Hesap Güvenliği: Account Security
          Kullanım Geçmişi: Login Logout History
          Grup Bilgileri: Group Information
          Ana Sayfa: Home Page
          Kurulum: Installation
          Sunucu Kurulumu(Lider): Server Installation(Lider)
          İstemci Kurulumu(Ahenk): Client Installation(Ahenk)
          Sistem Gereksinimleri: System Requirements

          #English navbar translate v2.0
          Kullanım: Usage
          Uzak Masaüstü: Remote Access
          İstemci Paket Depoları: Client Repository
          İstemci Paketlerini Listele ve Kaldır: List Package of Client and Remove Package
          Paket Kur ve Kaldır: İnstall and Remove Package
          Betik Listesi: List Script
          Betik Tanımı: Define Script
          Ahenk Kur: İnstall Ahenk
          Grup Yönetimi: Group Management
          Kullanıcı İşlemleri: User Operations
          Ad Senkronizasyon: AD Sync
          Genel Ekran: General Information
          Sistem: System
          Paket: Package
          Kullanıcı Yetkilendirme (Sudo): User Privilege (Sudo)
          Detaylı İştemci Raporu: Detail Agent Report
          Çalıştırılan Görevler Raporu: Executed Task Report
          Konsol Kullanıcısı Ayarları: Console User Settings
          LDAP Erişim Ayarları: LDAP Settings
          XMPP Ayarları: XMPP Settings
          LDAP Ayarları: LDAP Settings
          Diğer Ayarları: Other Settings
          Dosya Sunucu Ayarları: File Server Settings
          Sistem Gözlemcisi Tanımlama: Define System Monitoring
          Lider 3.0 Sürümüne Yükseltme: Upgrade to Lider 3.0
